[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pip-chill"
version = "1.0.4"
description = "Lists installed packages that are not dependencies of others"
authors = [{ name = "Ricardo BÃ¡nffy", email = "rbanffy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
license-files = ["LICENSE"]
keywords = ["pip", "dependencies", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = ["packaging>=23.0"]

[project.optional-dependencies]
dev = [
    "bandit",
    "flake8",
    "pre-commit",
    "pylint",
    "pytest",
    "setuptools_scm",
    "tox",
]

[tool.setuptools.packages.find]
where = ["pip_chill"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"

[tool.bandit.assert_used]
skips = ["*/test_*.py", "*/test_*.py"]

[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312", "py313"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["pip_chill"]
multi_line_output = 3
include_trailing_comma = true
