[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pip-chill"
version = "1.0.4"
description = "Lists installed packages that are not dependencies of others"
authors = [{ name = "Ricardo BÃ¡nffy", email = "rbanffy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["pip", "dependencies", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["packaging>=23.0"]

[project.optional-dependencies]
dev = [
    "bandit",
    "flake8",
    "pre-commit",
    "pylint",
    "pytest",
    "setuptools_scm",
    "tox",
]

[tool.setuptools.packages.find]
where = ["pip_chill"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311", "py312", "py313"]

[tool.isort]
profile = "black"

[tool.flake8]
exclude = ["docs"]
